name=LineFollower
version=1.0.0
author=King Diaw
maintainer=King Diaw <kingdiawehsut@gmail.com>
sentence=Library navigasi Line Follower untuk ESP32 menggunakan sensor I2C.
paragraph=Library aras tinggi (high-level) untuk memudahkan robot mengekori garisan, mengira persimpangan, dan membelok tepat 90/180 darjah secara automatik. Sesuai untuk navigasi grid.
category=Device Control
url=https://github.com/kingdiaw/LineFollower
architectures=esp32, *
depends=TwoWDController